[2025-04-14 23:44:32,764: INFO: main: Hello, World!]
[2025-04-15 00:54:19,962: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 00:54:19,967: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 00:55:07,920: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 00:55:07,924: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 12:50:22,891: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 12:50:22,892: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 12:55:21,442: ERROR: 1776682326: An error occurred: [Errno 2] No such file or directory: 'config/config.yaml']
Traceback (most recent call last):
  File "/var/folders/kx/d1gxzt7s111d0z9bjypgv2980000gn/T/ipykernel_1223/1776682326.py", line 2, in <module>
    config = ConfigurationManager()
  File "/var/folders/kx/d1gxzt7s111d0z9bjypgv2980000gn/T/ipykernel_1223/239571935.py", line 8, in __init__
    self.config = read_yaml(config_filepath)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/utils/common.py", line 36, in read_yaml
    raise e
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/utils/common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2025-04-15 13:11:38,977: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 13:11:38,978: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 13:11:38,979: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 13:14:36,930: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 13:14:36,932: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 13:14:36,933: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 13:15:52,884: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 13:15:52,885: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 13:15:52,886: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:21:54,055: INFO: main: Hello, World!]
[2025-04-15 14:50:06,400: INFO: common: yaml file: config.yaml loaded successfully]
[2025-04-15 14:50:06,402: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 14:50:06,403: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:53:53,382: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 14:53:53,384: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 14:53:53,386: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:53:53,387: INFO: common: created directory at: artifacts]
[2025-04-15 14:53:53,388: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 14:53:54,358: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: AE3E:2FD7C0:3FE5FC:AD9499:67FE25A9
Accept-Ranges: bytes
Date: Tue, 15 Apr 2025 09:23:54 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830049-CCU
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1744709034.078917,VS0,VE293
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 55e4d6acc5a5b0edd90817cd9f723849aafaf8d1
Expires: Tue, 15 Apr 2025 09:28:54 GMT
Source-Age: 0

]
[2025-04-15 14:54:46,814: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 14:54:46,815: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 14:54:46,816: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:54:46,817: INFO: common: created directory at: artifacts]
[2025-04-15 14:54:46,817: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 14:55:41,727: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 14:55:41,728: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 14:55:41,729: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:55:41,729: INFO: common: created directory at: artifacts]
[2025-04-15 14:55:41,730: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 14:55:41,741: INFO: 741865018: Splited data into training and test sets]
[2025-04-15 14:55:41,742: INFO: 741865018: (1199, 12)]
[2025-04-15 14:55:41,742: INFO: 741865018: (400, 12)]
[2025-04-15 14:56:03,395: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 14:56:03,397: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 14:56:03,399: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:56:03,399: INFO: common: created directory at: artifacts]
[2025-04-15 14:56:03,400: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 14:56:23,184: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 14:56:23,185: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 14:56:23,186: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 14:56:23,187: INFO: common: created directory at: artifacts]
[2025-04-15 14:56:23,187: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 14:56:24,118: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 15:17:03,246: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:17:03,248: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:17:03,248: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:17:03,249: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:17:03,249: INFO: common: created directory at: artifacts]
[2025-04-15 15:17:03,249: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:17:04,239: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: AE3E:2FD7C0:3FE5FC:AD9499:67FE25A9
Accept-Ranges: bytes
Date: Tue, 15 Apr 2025 09:47:04 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830033-CCU
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1744710424.963230,VS0,VE269
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 5222a14c749daf956f563a82a7f86e3a07d3740a
Expires: Tue, 15 Apr 2025 09:52:04 GMT
Source-Age: 0

]
[2025-04-15 15:17:04,243: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:31:14,796: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:31:14,797: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:31:14,798: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:31:14,799: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:31:14,799: INFO: common: created directory at: artifacts]
[2025-04-15 15:31:14,799: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:31:14,799: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:31:14,801: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:31:14,802: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:31:14,803: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:31:14,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:31:14,804: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:31:14,804: INFO: common: created directory at: artifacts]
[2025-04-15 15:31:14,804: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:31:14,809: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:35:52,381: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:35:52,382: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:35:52,383: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:35:52,384: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:35:52,384: INFO: common: created directory at: artifacts]
[2025-04-15 15:35:52,384: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:35:52,384: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:35:52,386: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:35:52,386: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:35:52,387: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:35:52,387: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:35:52,388: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:35:52,388: INFO: common: created directory at: artifacts]
[2025-04-15 15:35:52,388: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:35:52,400: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:36:08,304: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:36:08,306: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:36:08,306: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:36:08,307: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:36:08,307: INFO: common: created directory at: artifacts]
[2025-04-15 15:36:08,307: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:36:08,308: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:36:08,310: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:36:08,310: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:36:08,311: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:36:08,311: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:36:08,314: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:36:08,315: INFO: common: created directory at: artifacts]
[2025-04-15 15:36:08,315: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:36:08,321: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:36:20,136: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:36:20,140: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:36:20,141: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:36:20,143: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:36:20,143: INFO: common: created directory at: artifacts]
[2025-04-15 15:36:20,143: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:36:20,143: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:36:20,145: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:36:20,145: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:36:20,156: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:36:20,157: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:36:20,158: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:36:20,158: INFO: common: created directory at: artifacts]
[2025-04-15 15:36:20,158: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:36:20,161: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:40:26,118: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:40:26,120: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:40:26,121: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:40:26,121: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:40:26,122: INFO: common: created directory at: artifacts]
[2025-04-15 15:40:26,122: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:40:26,122: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:40:26,123: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:40:26,123: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:40:26,125: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:40:26,125: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:40:26,126: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:40:26,126: INFO: common: created directory at: artifacts]
[2025-04-15 15:40:26,126: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:40:26,129: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:41:32,758: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:41:32,759: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:41:32,760: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:41:32,761: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:41:32,761: INFO: common: created directory at: artifacts]
[2025-04-15 15:41:32,761: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:41:32,761: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:41:32,762: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:41:32,762: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:41:32,764: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:41:32,764: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:41:32,765: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:41:32,765: INFO: common: created directory at: artifacts]
[2025-04-15 15:41:32,765: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:41:32,768: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:43:59,797: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:43:59,798: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:43:59,799: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:43:59,800: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:43:59,800: INFO: common: created directory at: artifacts]
[2025-04-15 15:43:59,800: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:43:59,800: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:43:59,802: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:43:59,802: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:43:59,803: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:43:59,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:43:59,804: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:43:59,804: INFO: common: created directory at: artifacts]
[2025-04-15 15:43:59,804: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:43:59,808: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:43:59,808: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:43:59,809: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:43:59,809: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:43:59,810: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:43:59,810: INFO: common: created directory at: artifacts]
[2025-04-15 15:43:59,810: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:43:59,821: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:43:59,821: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:43:59,821: INFO: data_transformation: (400, 12)]
[2025-04-15 15:43:59,821: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:44:46,665: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:44:46,666: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:44:46,667: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:44:46,667: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:44:46,667: INFO: common: created directory at: artifacts]
[2025-04-15 15:44:46,667: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:44:46,667: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:44:46,669: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:44:46,669: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:44:46,670: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:44:46,671: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:44:46,671: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:44:46,672: INFO: common: created directory at: artifacts]
[2025-04-15 15:44:46,672: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:44:46,677: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:44:46,677: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:44:46,678: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:44:46,679: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:44:46,680: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:44:46,680: INFO: common: created directory at: artifacts]
[2025-04-15 15:44:46,680: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:44:46,698: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:44:46,698: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:44:46,698: INFO: data_transformation: (400, 12)]
[2025-04-15 15:44:46,698: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:45:01,112: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:45:01,114: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:45:01,114: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:45:01,115: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:45:01,115: INFO: common: created directory at: artifacts]
[2025-04-15 15:45:01,115: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:45:01,115: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:45:01,117: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:45:01,117: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:45:01,118: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:45:01,118: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:45:01,119: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:45:01,119: INFO: common: created directory at: artifacts]
[2025-04-15 15:45:01,119: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:45:01,124: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:45:01,124: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:45:01,126: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:45:01,126: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:45:01,127: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:45:01,127: INFO: common: created directory at: artifacts]
[2025-04-15 15:45:01,127: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:45:01,137: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:45:01,137: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:45:01,137: INFO: data_transformation: (400, 12)]
[2025-04-15 15:45:01,137: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:47:50,966: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:47:50,968: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:47:50,969: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:47:50,971: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:47:50,971: INFO: common: created directory at: artifacts]
[2025-04-15 15:47:50,971: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:47:50,971: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:47:50,974: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:47:50,974: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:47:50,976: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:47:50,978: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:47:50,979: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:47:50,979: INFO: common: created directory at: artifacts]
[2025-04-15 15:47:50,980: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:47:50,984: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:47:50,984: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:47:50,985: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:47:50,986: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:47:50,987: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:47:50,987: INFO: common: created directory at: artifacts]
[2025-04-15 15:47:50,987: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:47:50,998: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:47:50,998: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:47:50,998: INFO: data_transformation: (400, 12)]
[2025-04-15 15:47:50,999: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:47:50,999: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:47:51,000: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:47:51,000: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:47:51,001: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:47:51,001: INFO: common: created directory at: artifacts]
[2025-04-15 15:47:51,001: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:47:51,006: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:48:21,211: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:48:21,213: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:48:21,214: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:48:21,214: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:48:21,215: INFO: common: created directory at: artifacts]
[2025-04-15 15:48:21,215: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:48:21,215: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:48:21,216: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:48:21,216: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:48:21,217: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:48:21,218: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:48:21,218: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:48:21,219: INFO: common: created directory at: artifacts]
[2025-04-15 15:48:21,219: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:48:21,226: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:48:21,226: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:48:21,228: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:48:21,228: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:48:21,229: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:48:21,229: INFO: common: created directory at: artifacts]
[2025-04-15 15:48:21,230: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:48:21,244: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:48:21,244: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:48:21,244: INFO: data_transformation: (400, 12)]
[2025-04-15 15:48:21,244: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:48:21,245: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:48:21,246: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:48:21,246: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:48:21,247: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:48:21,247: INFO: common: created directory at: artifacts]
[2025-04-15 15:48:21,247: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:48:21,253: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:50:26,473: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:50:26,475: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:50:26,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:50:26,477: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:50:26,477: INFO: common: created directory at: artifacts]
[2025-04-15 15:50:26,477: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:50:26,477: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:50:26,478: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:50:26,478: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:50:26,479: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:50:26,480: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:50:26,481: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:50:26,481: INFO: common: created directory at: artifacts]
[2025-04-15 15:50:26,481: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:50:26,484: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:50:26,484: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:50:26,485: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:50:26,485: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:50:26,486: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:50:26,486: INFO: common: created directory at: artifacts]
[2025-04-15 15:50:26,486: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:50:26,495: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:50:26,495: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:50:26,495: INFO: data_transformation: (400, 12)]
[2025-04-15 15:50:26,495: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:50:26,495: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:50:26,497: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:50:26,497: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:50:26,498: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:50:26,498: INFO: common: created directory at: artifacts]
[2025-04-15 15:50:26,498: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:50:26,516: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:50:26,516: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 15:50:26,519: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:50:26,520: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:50:26,522: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:50:26,522: INFO: common: created directory at: artifacts]
[2025-04-15 15:50:26,522: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 15:50:26,601: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 15:50:27,943: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 15:52:20,684: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:52:20,686: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:52:20,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:52:20,687: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:52:20,687: INFO: common: created directory at: artifacts]
[2025-04-15 15:52:20,687: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:52:20,688: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:52:20,689: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:52:20,689: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:52:20,690: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:52:20,691: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:52:20,691: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:52:20,692: INFO: common: created directory at: artifacts]
[2025-04-15 15:52:20,692: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:52:20,697: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:52:20,697: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:52:20,699: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:52:20,699: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:52:20,700: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:52:20,700: INFO: common: created directory at: artifacts]
[2025-04-15 15:52:20,700: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:52:20,711: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:52:20,711: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:52:20,711: INFO: data_transformation: (400, 12)]
[2025-04-15 15:52:20,711: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:52:20,711: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:52:20,712: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:52:20,713: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:52:20,713: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:52:20,713: INFO: common: created directory at: artifacts]
[2025-04-15 15:52:20,714: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:52:20,720: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:52:20,720: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 15:52:20,721: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:52:20,722: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:52:20,741: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:52:20,741: INFO: common: created directory at: artifacts]
[2025-04-15 15:52:20,741: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 15:52:20,809: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 15:52:22,193: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 15:54:03,193: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:54:03,194: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:03,195: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:03,196: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:03,196: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:03,196: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:54:03,196: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:54:03,197: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:54:03,197: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:54:03,198: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:03,199: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:03,199: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:03,199: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:03,200: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:54:03,206: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:54:03,206: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:54:03,207: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:03,207: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:03,208: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:03,208: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:03,208: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:54:03,222: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:54:03,222: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:54:03,222: INFO: data_transformation: (400, 12)]
[2025-04-15 15:54:03,222: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:54:03,222: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:54:03,229: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:03,230: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:03,230: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:03,230: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:03,230: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:54:03,275: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:54:03,276: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 15:54:03,277: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:03,277: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:03,278: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:03,278: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:03,278: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 15:54:03,410: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 15:54:04,798: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 15:54:43,914: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:54:43,915: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:43,916: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:43,917: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:43,917: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:43,917: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:54:43,917: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:54:43,918: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:54:43,918: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:54:43,920: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:43,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:43,921: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:43,921: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:43,921: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:54:43,927: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:54:43,927: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:54:43,928: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:43,928: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:43,929: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:43,929: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:43,929: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:54:43,941: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:54:43,941: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:54:43,941: INFO: data_transformation: (400, 12)]
[2025-04-15 15:54:43,942: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:54:43,942: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:54:43,943: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:43,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:43,944: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:43,945: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:43,945: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:54:43,975: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:54:43,975: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 15:54:43,977: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:54:43,978: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:54:43,980: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:54:43,980: INFO: common: created directory at: artifacts]
[2025-04-15 15:54:43,981: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 15:54:44,074: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 15:54:45,407: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 15:56:58,607: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 15:56:58,610: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:56:58,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:56:58,612: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:56:58,612: INFO: common: created directory at: artifacts]
[2025-04-15 15:56:58,612: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 15:56:58,612: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 15:56:58,614: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 15:56:58,614: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 15:56:58,616: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:56:58,616: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:56:58,617: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:56:58,617: INFO: common: created directory at: artifacts]
[2025-04-15 15:56:58,617: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 15:56:58,623: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 15:56:58,623: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 15:56:58,626: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:56:58,626: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:56:58,627: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:56:58,627: INFO: common: created directory at: artifacts]
[2025-04-15 15:56:58,627: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 15:56:58,644: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 15:56:58,644: INFO: data_transformation: (1199, 12)]
[2025-04-15 15:56:58,644: INFO: data_transformation: (400, 12)]
[2025-04-15 15:56:58,644: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 15:56:58,644: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 15:56:58,645: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:56:58,645: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:56:58,646: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:56:58,646: INFO: common: created directory at: artifacts]
[2025-04-15 15:56:58,646: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 15:56:58,660: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 15:56:58,661: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 15:56:58,662: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 15:56:58,662: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 15:56:58,663: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 15:56:58,663: INFO: common: created directory at: artifacts]
[2025-04-15 15:56:58,663: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 15:56:58,744: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 15:57:00,076: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 16:18:38,950: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:18:38,951: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:18:38,952: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:18:38,953: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:18:38,953: INFO: common: created directory at: artifacts]
[2025-04-15 16:18:38,953: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:18:38,953: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:18:38,954: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:18:38,954: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:18:38,956: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:18:38,956: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:18:38,957: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:18:38,957: INFO: common: created directory at: artifacts]
[2025-04-15 16:18:38,957: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:18:38,960: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:18:38,960: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:18:38,961: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:18:38,963: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:18:38,966: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:18:38,966: INFO: common: created directory at: artifacts]
[2025-04-15 16:18:38,967: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:18:38,979: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:18:38,979: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:18:38,979: INFO: data_transformation: (400, 12)]
[2025-04-15 16:18:38,979: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:18:38,979: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:18:38,981: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:18:38,981: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:18:38,982: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:18:38,982: INFO: common: created directory at: artifacts]
[2025-04-15 16:18:38,982: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:18:38,994: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:18:38,994: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:18:38,995: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:18:38,996: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:18:38,996: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:18:38,996: INFO: common: created directory at: artifacts]
[2025-04-15 16:18:38,996: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:18:39,068: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:18:40,534: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 16:22:37,789: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:22:37,791: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:22:37,791: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:22:37,792: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:22:37,792: INFO: common: created directory at: artifacts]
[2025-04-15 16:22:37,792: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:22:37,792: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:22:37,794: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:22:37,794: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:22:37,795: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:22:37,796: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:22:37,797: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:22:37,797: INFO: common: created directory at: artifacts]
[2025-04-15 16:22:37,797: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:22:37,801: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:22:37,801: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:22:37,802: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:22:37,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:22:37,803: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:22:37,803: INFO: common: created directory at: artifacts]
[2025-04-15 16:22:37,803: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:22:37,818: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:22:37,818: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:22:37,818: INFO: data_transformation: (400, 12)]
[2025-04-15 16:22:37,818: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:22:37,818: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:22:37,819: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:22:37,820: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:22:37,820: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:22:37,820: INFO: common: created directory at: artifacts]
[2025-04-15 16:22:37,820: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:22:37,828: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:22:37,828: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:22:37,829: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:22:37,830: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:22:37,830: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:22:37,830: INFO: common: created directory at: artifacts]
[2025-04-15 16:22:37,830: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:22:37,904: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:22:39,283: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 16:23:38,543: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:23:38,545: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:23:38,545: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:23:38,546: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:23:38,546: INFO: common: created directory at: artifacts]
[2025-04-15 16:23:38,546: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:23:38,546: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:23:38,548: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:23:38,548: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:23:38,549: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:23:38,549: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:23:38,550: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:23:38,550: INFO: common: created directory at: artifacts]
[2025-04-15 16:23:38,550: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:23:38,556: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:23:38,556: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:23:38,557: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:23:38,557: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:23:38,558: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:23:38,558: INFO: common: created directory at: artifacts]
[2025-04-15 16:23:38,558: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:23:38,574: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:23:38,574: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:23:38,574: INFO: data_transformation: (400, 12)]
[2025-04-15 16:23:38,575: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:23:38,575: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:23:38,576: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:23:38,576: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:23:38,577: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:23:38,577: INFO: common: created directory at: artifacts]
[2025-04-15 16:23:38,577: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:23:38,586: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:23:38,586: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:23:38,589: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:23:38,589: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:23:38,591: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:23:38,592: INFO: common: created directory at: artifacts]
[2025-04-15 16:23:38,592: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:23:38,664: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:23:40,027: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 16:28:49,406: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:28:49,408: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:28:49,408: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:28:49,409: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:28:49,409: INFO: common: created directory at: artifacts]
[2025-04-15 16:28:49,409: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:28:49,409: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:28:49,412: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:28:49,412: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:28:49,412: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:28:49,413: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:28:49,413: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:28:49,413: INFO: common: created directory at: artifacts]
[2025-04-15 16:28:49,413: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:28:49,418: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:28:49,418: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:28:49,419: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:28:49,419: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:28:49,420: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:28:49,420: INFO: common: created directory at: artifacts]
[2025-04-15 16:28:49,420: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:28:49,429: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:28:49,430: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:28:49,430: INFO: data_transformation: (400, 12)]
[2025-04-15 16:28:49,430: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:28:49,430: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:28:49,430: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:28:49,431: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:28:49,439: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:28:49,440: INFO: common: created directory at: artifacts]
[2025-04-15 16:28:49,440: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:28:49,452: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:28:49,452: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:28:49,453: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:28:49,453: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:28:49,454: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:28:49,454: INFO: common: created directory at: artifacts]
[2025-04-15 16:28:49,454: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:28:49,516: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:28:50,970: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/setuptools/_distutils/dir_util.py", line 150, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/setuptools/_distutils/dir_util.py", line 192, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.11/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 16:33:29,870: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:33:29,872: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:33:29,873: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:33:29,873: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:33:29,874: INFO: common: created directory at: artifacts]
[2025-04-15 16:33:29,874: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:33:29,874: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:33:29,876: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:33:29,876: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:33:29,877: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:33:29,878: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:33:29,878: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:33:29,878: INFO: common: created directory at: artifacts]
[2025-04-15 16:33:29,878: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:33:29,881: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:33:29,881: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:33:29,883: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:33:29,883: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:33:29,884: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:33:29,884: INFO: common: created directory at: artifacts]
[2025-04-15 16:33:29,884: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:33:29,894: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:33:29,894: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:33:29,894: INFO: data_transformation: (400, 12)]
[2025-04-15 16:33:29,894: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:33:29,894: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:33:29,895: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:33:29,895: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:33:29,896: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:33:29,896: INFO: common: created directory at: artifacts]
[2025-04-15 16:33:29,896: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:33:29,902: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:33:29,902: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:33:29,906: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:33:29,906: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:33:29,907: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:33:29,907: INFO: common: created directory at: artifacts]
[2025-04-15 16:33:29,907: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:33:30,000: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:33:31,370: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 66, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/setuptools/_distutils/file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-04-15 16:52:38,766: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:52:38,767: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:52:38,768: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:52:38,768: INFO: common: created directory at: artifacts]
[2025-04-15 16:52:38,769: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:53:36,458: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:53:36,460: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:53:36,461: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:53:36,461: INFO: common: created directory at: artifacts]
[2025-04-15 16:53:36,461: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:53:48,411: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:53:48,412: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:53:48,413: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:53:48,414: INFO: common: created directory at: artifacts]
[2025-04-15 16:53:48,414: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:55:27,875: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:55:27,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:55:27,877: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:55:27,877: INFO: common: created directory at: artifacts]
[2025-04-15 16:55:27,878: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:55:28,734: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:57:40,524: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:57:40,525: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:57:40,526: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:57:40,527: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:57:40,527: INFO: common: created directory at: artifacts]
[2025-04-15 16:57:40,527: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:57:40,527: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:57:40,529: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:57:40,529: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:57:40,530: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:57:40,531: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:57:40,531: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:57:40,531: INFO: common: created directory at: artifacts]
[2025-04-15 16:57:40,532: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:57:40,537: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:57:40,537: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:57:40,538: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:57:40,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:57:40,539: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:57:40,539: INFO: common: created directory at: artifacts]
[2025-04-15 16:57:40,539: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:57:40,551: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:57:40,551: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:57:40,551: INFO: data_transformation: (400, 12)]
[2025-04-15 16:57:40,551: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:57:40,551: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:57:40,552: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:57:40,552: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:57:40,553: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:57:40,553: INFO: common: created directory at: artifacts]
[2025-04-15 16:57:40,553: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:57:40,562: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:57:40,562: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:57:40,564: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:57:40,568: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:57:40,600: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:57:40,601: INFO: common: created directory at: artifacts]
[2025-04-15 16:57:40,601: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:57:41,226: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
==========================================']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 40, in log_into_mlflow
    with mlflow.start_run():
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 131, in create_run
    return self.store.create_run(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
=========================================='
[2025-04-15 16:59:35,621: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 16:59:35,622: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:59:35,623: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:59:35,624: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:59:35,624: INFO: common: created directory at: artifacts]
[2025-04-15 16:59:35,624: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 16:59:35,624: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 16:59:35,626: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 16:59:35,626: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 16:59:35,627: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:59:35,627: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:59:35,628: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:59:35,628: INFO: common: created directory at: artifacts]
[2025-04-15 16:59:35,628: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 16:59:35,630: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 16:59:35,631: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 16:59:35,632: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:59:35,632: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:59:35,633: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:59:35,633: INFO: common: created directory at: artifacts]
[2025-04-15 16:59:35,633: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 16:59:35,641: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 16:59:35,641: INFO: data_transformation: (1199, 12)]
[2025-04-15 16:59:35,641: INFO: data_transformation: (400, 12)]
[2025-04-15 16:59:35,641: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 16:59:35,641: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 16:59:35,642: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:59:35,643: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:59:35,643: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:59:35,643: INFO: common: created directory at: artifacts]
[2025-04-15 16:59:35,643: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 16:59:35,650: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 16:59:35,650: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 16:59:35,651: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 16:59:35,651: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 16:59:35,652: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 16:59:35,652: INFO: common: created directory at: artifacts]
[2025-04-15 16:59:35,652: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 16:59:36,472: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 16:59:44,273: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 64, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model", registered_model_name="ElasticnetModel")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 562, in log
    mlflow.register_model(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_model_registry/fluent.py", line 77, in register_model
    raise e
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_model_registry/fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/model_registry/rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/model_registry/base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2025-04-15 17:03:30,307: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:03:30,308: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:03:30,309: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:03:30,310: INFO: common: created directory at: artifacts]
[2025-04-15 17:03:30,310: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 17:03:31,075: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 17:05:03,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 17:05:03,097: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:05:03,097: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:05:03,098: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:05:03,098: INFO: common: created directory at: artifacts]
[2025-04-15 17:05:03,098: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 17:05:03,098: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 17:05:03,100: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 17:05:03,100: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 17:05:03,102: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:05:03,102: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:05:03,103: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:05:03,103: INFO: common: created directory at: artifacts]
[2025-04-15 17:05:03,103: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 17:05:03,106: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 17:05:03,106: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 17:05:03,107: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:05:03,107: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:05:03,108: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:05:03,108: INFO: common: created directory at: artifacts]
[2025-04-15 17:05:03,108: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 17:05:03,117: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 17:05:03,117: INFO: data_transformation: (1199, 12)]
[2025-04-15 17:05:03,117: INFO: data_transformation: (400, 12)]
[2025-04-15 17:05:03,117: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 17:05:03,117: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 17:05:03,118: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:05:03,119: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:05:03,119: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:05:03,119: INFO: common: created directory at: artifacts]
[2025-04-15 17:05:03,120: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 17:05:03,127: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 17:05:03,127: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 17:05:03,128: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:05:03,128: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:05:03,129: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:05:03,129: INFO: common: created directory at: artifacts]
[2025-04-15 17:05:03,129: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 17:05:03,950: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 17:05:12,465: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data_ingestion.main()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/pipeline/stage_05_model_evaluation.py", line 15, in main
    model_evaluation_config.log_into_mlflow()
  File "/Users/preetyrai/Full_Stack_ML_Project/End-to-End-Machine-Learning-Project---Drug-Quality/src/mlProject/components/model_evaluation.py", line 64, in log_into_mlflow
    mlflow.sklearn.log_model(model, "model", registered_model_name="ElasticnetModel")
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 424, in log_model
    return Model.log(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/models/model.py", line 562, in log
    mlflow.register_model(
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_model_registry/fluent.py", line 77, in register_model
    raise e
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_model_registry/fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/model_registry/rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/store/model_registry/base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/opt/anaconda3/envs/mlenv/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2025-04-15 17:11:05,889: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-15 17:11:05,890: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:11:05,891: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:11:05,892: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:11:05,892: INFO: common: created directory at: artifacts]
[2025-04-15 17:11:05,892: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-15 17:11:05,892: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2025-04-15 17:11:05,893: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-15 17:11:05,893: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-04-15 17:11:05,895: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:11:05,895: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:11:05,896: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:11:05,896: INFO: common: created directory at: artifacts]
[2025-04-15 17:11:05,896: INFO: common: created directory at: artifacts/data_validation]
[2025-04-15 17:11:05,900: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-04-15 17:11:05,900: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-04-15 17:11:05,901: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:11:05,902: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:11:05,903: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:11:05,903: INFO: common: created directory at: artifacts]
[2025-04-15 17:11:05,903: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-15 17:11:05,912: INFO: data_transformation: Splited data into training and test sets]
[2025-04-15 17:11:05,912: INFO: data_transformation: (1199, 12)]
[2025-04-15 17:11:05,912: INFO: data_transformation: (400, 12)]
[2025-04-15 17:11:05,912: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-04-15 17:11:05,912: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-04-15 17:11:05,913: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:11:05,913: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:11:05,914: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:11:05,914: INFO: common: created directory at: artifacts]
[2025-04-15 17:11:05,914: INFO: common: created directory at: artifacts/model_trainer]
[2025-04-15 17:11:05,921: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-04-15 17:11:05,921: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-04-15 17:11:05,922: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-15 17:11:05,923: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-15 17:11:05,923: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-15 17:11:05,924: INFO: common: created directory at: artifacts]
[2025-04-15 17:11:05,924: INFO: common: created directory at: artifacts/model_evaluation]
[2025-04-15 17:11:06,579: INFO: common: json file saved at: artifacts/model_evaluation/metrics.json]
[2025-04-15 17:11:15,372: INFO: main: >>>>>> stage Model evaluation stage completed <<<<<<

x==========x]
